### ISSUE TITLE
__uri()转换后，如何把url给tpl呢

### ISSUE THREAD

**Issue by xjchenhao** [xiangshouding/fis-preprocessor-extlang#3]
作者您好，
我的tpl文件里有一个图片链接需要被fis编译，通过您的`fis-preprocessor-extlang`插件，我把url转换成想要的路径了，但是fis的__uri()方法只能与变量赋值一起使用`var a = __uri('./c.js')`，那我怎么把这个变量还给tpl文件，让tpl文件把图片加载出来呢？

**Comment by oxUnd** [comment]
让这个图片入表，如何入表呢

``` js
fis.config.set('roadmap.path', [
  {
    reg: /xxx.png/, //某图片
    release: '/static/$0' //产出到什么地方
  }
].concat(fis.config.get('roadmap.path', [])));
```

然后在 tpl 中用 

``` smarty
{%uri name="某图片的ID"%}
```

**Comment by xjchenhao** [comment]
某图片的ID其实就是图片的路径? 这种方式，要是图片特别多的话，配置起来会很麻烦欸.

**Comment by oxUnd** [comment]
@xjchenhao 那解决你的问题了没有？

**Comment by xjchenhao** [comment]
解决了，谢谢^_^
